# Generated by Django 4.0.2 on 2022-02-27 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blognews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=1000)),
                ('arrival_date', models.CharField(max_length=500)),
                ('Cover_pic', models.ImageField(upload_to='photos')),
                ('Cover_pic1', models.ImageField(blank=True, upload_to='photos')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
