# Generated by Django 4.0.2 on 2022-03-03 10:24

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognews',
            name='discreptation',
            field=ckeditor.fields.RichTextField(default=1),
        ),
        migrations.AddField(
            model_name='blognews',
            name='writer',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
