# Generated by Django 4.0.2 on 2022-02-27 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%M/%d/')),
                ('facebook', models.URLField()),
                ('google', models.URLField()),
                ('twitter', models.URLField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos')),
                ('image1', models.ImageField(upload_to='photos')),
                ('discreptation', models.TextField(max_length=5000)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
