# Generated by Django 4.0.2 on 2022-02-27 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House_property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=1000)),
                ('house_no', models.IntegerField()),
                ('image', models.ImageField(upload_to='photos')),
                ('image1', models.ImageField(blank=True, upload_to='photos')),
                ('image2', models.ImageField(blank=True, upload_to='photos')),
                ('image3', models.ImageField(blank=True, upload_to='photos')),
                ('image4', models.ImageField(blank=True, upload_to='photos')),
                ('image5', models.ImageField(blank=True, upload_to='photos')),
                ('state', models.CharField(choices=[('PU', 'punjab'), ('KPK', 'khyber pukhtankhwa'), ('BL', 'blochistan'), ('FD', 'fedral Territory'), ('SN', 'sindh'), ('KS', 'kashmir')], max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('condition', models.CharField(max_length=100)),
                ('Rent', models.CharField(max_length=5000)),
                ('Area', models.CharField(max_length=500)),
                ('BedsRoom', models.IntegerField()),
                ('Bath', models.IntegerField()),
                ('Garages', models.IntegerField()),
                ('no_of_owners', models.CharField(max_length=100)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
