# Generated by Django 4.0.2 on 2022-03-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0002_remove_house_property_rent_house_property_amenities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house_property',
            name='Location',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
