# Generated by Django 4.0.2 on 2022-03-01 06:44

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_alter_house_property_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house_property',
            name='Location',
        ),
        migrations.AddField(
            model_name='house_property',
            name='price',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house_property',
            name='Amenities',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Balcony', 'Balcony'), ('Deck', 'Deck'), ('Parking', 'Parking'), ('Outdoor Kitchen', 'Outdoor Kitchen'), ('Tennis Courts', 'Tennis Courts'), ('Sun Room', 'Sun Room'), ('Cable Tv', 'Cable Tv'), ('Internet', 'Internet'), ('Garden', 'Garden'), ('Concrete Flooring', 'Concrete Flooring')], default=111, max_length=102),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house_property',
            name='Status',
            field=models.CharField(choices=[('sale', 'sale'), ('Rent', 'Rent')], max_length=5000),
        ),
    ]
