# Generated by Django 4.0.2 on 2022-03-01 10:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_remove_house_property_location_house_property_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_property',
            name='Description',
            field=ckeditor.fields.RichTextField(default=1122),
            preserve_default=False,
        ),
    ]
