# Generated by Django 4.0.2 on 2022-03-02 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_testimonial_discreptation'),
        ('house', '0005_house_property_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_property',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.agent'),
        ),
    ]
