# Generated by Django 4.0.2 on 2022-03-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_house_property_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house_property',
            name='name',
        ),
        migrations.AlterField(
            model_name='house_property',
            name='house_no',
            field=models.CharField(max_length=400),
        ),
    ]
