# Generated by Django 4.0.2 on 2022-03-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_remove_house_property_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house_property',
            name='Ubication',
            field=models.URLField(default=1, max_length=5000),
        ),
        migrations.AddField(
            model_name='house_property',
            name='video',
            field=models.URLField(default=1, max_length=50000),
        ),
    ]
